kind: pipeline
name: default

steps:
  - name: eqemu-admin-build
    image: akkadius/eqemu:eqemu-admin-build-5-31-2020
    environment:
      GH_RELEASE_GITHUB_API_TOKEN:
        from_secret: token
    commands:
      - sudo -E deploy/scripts/build-in-container.sh
      - ./node_modules/.bin/gh-release --assets=eqemu-admin-linux,eqemu-admin-win.exe -y
    when:
      branch: ["release"]
      event: [push]
