kind: pipeline
name: default

steps:
  - name: eqemu-admin-build
    image: akkadius/eqemu:eqemu-admin-build-latest
    environment:
      GH_RELEASE_GITHUB_API_TOKEN:
        from_secret: token
    commands:
      - sudo deploy/scripts/build-in-container.sh
    when:
      branch: ["master"]
      event: [push]
