pipeline:
  run-build:
    image: akkadius/eqemu:eqemu-admin-build-latest
    commands:
      - sudo deploy/scripts/build-in-container.sh
    secrets:
      - source: GH_RELEASE_GITHUB_API_TOKEN
        target: GH_RELEASE_GITHUB_API_TOKEN
    when:
      branch: ["master"]
      event: [push]
