pipeline:
  run-build:
    image: akkadius/eqemu:eqemu-admin-build-latest
    commands:
      - sudo deploy/scripts/build-in-container.sh
    environment:
      GH_RELEASE_GITHUB_API_TOKEN:
        from_secret: GH_RELEASE_GITHUB_API_TOKEN
    when:
      branch: ["master"]
      event: [push]

