kind: pipeline
name: default

steps:
  - name: eqemu-admin-build
    image: akkadius/eqemu-admin-build-pipeline:latest
    environment:
      GH_RELEASE_GITHUB_API_TOKEN:
        from_secret: GH_RELEASE_GITHUB_API_TOKEN
    commands:
      - sudo -E deploy/scripts/build-in-container.sh
      - ./node_modules/.bin/gh-release --assets=eqemu-admin-linux,eqemu-admin-win.exe -y || echo "Already published release"
    when:
      branch: ["master"]
      event: [push]
